# -*- coding: utf-8 -*-
"""implementationipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FHLrP1kE7_WnCUUVEdJ4FwcdnstHt1Sw
"""

import math

# 8.3 Corpus
corpus = [
    "cat eats fish",
    "dog eats fish",
    "cat likes fish"
]

def build_vocabulary(corpus):
    vocab = set()
    for doc in corpus:
        vocab.update(doc.split())
    return sorted(list(vocab))

def compute_counts(doc, vocab):
    words = doc.split()
    return [words.count(w) for w in vocab]

def compute_tf(counts):
    total = sum(counts)
    return [c / total for c in counts] if total > 0 else [0.0] * len(counts)

def compute_idf(corpus, vocab):
    N = len(corpus)
    idf = []
    for w in vocab:
        df = sum(1 for doc in corpus if w in doc.split())
        idf.append(math.log10(N / df) if df > 0 else 0.0)
    return idf

def compute_tfidf(tf_vec, idf_vec):
    return [tf * idf for tf, idf in zip(tf_vec, idf_vec)]

def cosine_similarity(v1, v2):
    dot_product = sum(a * b for a, b in zip(v1, v2))
    norm1 = math.sqrt(sum(a * a for a in v1))
    norm2 = math.sqrt(sum(b * b for b in v2))
    return dot_product / (norm1 * norm2) if norm1 > 0 and norm2 > 0 else 0.0

vocab = build_vocabulary(corpus)
idf_vec = compute_idf(corpus, vocab)

tfidf_matrix = []
for doc in corpus:
    counts = compute_counts(doc, vocab)
    tf_vec = compute_tf(counts)
    tfidf = compute_tfidf(tf_vec, idf_vec)
    tfidf_matrix.append(tfidf)



assert build_vocabulary(corpus) == ['cat', 'dog', 'eats', 'fish', 'likes'], "Error build_vocabulary"

D1_counts = compute_counts(corpus[0], vocab)
assert D1_counts == [1, 0, 1, 1, 0], "Error compute_counts"

D1_tf = compute_tf(D1_counts)
assert abs(D1_tf[0] - 1/3) < 1e-9, "Error compute_tf"

assert abs(idf_vec[vocab.index('fish')] - 0.0) < 1e-9, "Error compute_idf"

expected_tfidf_cat = (1/3) * math.log10(3/2)
D1_tfidf = compute_tfidf(D1_tf, idf_vec)
assert abs(D1_tfidf[0] - expected_tfidf_cat) < 1e-9, "Error compute_tfidf"

v_x = [1, 1, 1]
v_y = [1, 1, 0]
assert abs(cosine_similarity(v_x, v_y) - (2 / math.sqrt(6))) < 1e-9, "Error cosine_similarity"

print("pass! (6/6)")
# 8.5 So sánh với thư viện (Scikit-Learn)
vectorizer = TfidfVectorizer()
sklearn_tfidf = vectorizer.fit_transform(corpus).toarray()

print("\n--- Compare : STUDENT vs SKLEARN ---")
print("Student TF-IDF D1:\n", [round(num, 4) for num in tfidf_matrix[0]])
print("Sklearn TF-IDF D1:\n", [round(num, 4) for num in sklearn_tfidf[0]])

"""### Giải thích sự khác biệt giữa Student Implementation và Sklearn

Dựa theo tài liệu chính thức của scikit-learn (`TfidfVectorizer`/`TfidfTransformer`), sự khác biệt nằm ở các điểm sau:

**1. Khác ở Công thức & Convention (Quan trọng nhất):**
* **TF (Term Frequency):** Code chay của ta tính theo tỉ lệ (count / tổng số từ trong câu). Sklearn mặc định chỉ lấy số đếm thô (raw count).
* **IDF (Inverse Document Frequency):**
  * Code chay dùng log cơ số 10: `log10(N / df)`.
  * Sklearn dùng logarit tự nhiên (`ln`). Mặc định có `smooth_idf=True` để tránh lỗi chia cho 0, công thức biến thành: `ln((N + 1) / (df + 1)) + 1`.
  * Số 1 cộng thêm giúp từ có mặt ở MỌI document (như "fish") sẽ có IDF = 1 thay vì triệt tiêu về 0.

**2. Khác ở Normalization (Chuẩn hóa):**
* Sau khi nhân $TF \times IDF$, Sklearn tự động áp dụng chuẩn hóa L2 (L2 normalization) (chia từng giá trị cho chiều dài Euclid của vector) để đưa độ dài vector về 1.
* Code chay chỉ tính đến tích $TF \times IDF$ rồi dừng lại.

**3. Khác ở Vocabulary ordering:**
* Sklearn tự động sắp xếp từ vựng theo thứ tự bảng chữ cái (alphabetical order). Code chay nếu dùng `set()` thuần túy mà không gọi hàm `sort()` thì thứ tự sẽ bị lệch.

**4. Khác ở Implementation:**
* Sklearn tính toán hoàn toàn trên cấu trúc ma trận thưa (CSR format của SciPy) để tối ưu bộ nhớ và tốc độ. Code chay thao tác trên lists/arrays cơ bản của Python.
"""