# -*- coding: utf-8 -*-
"""cooccurrence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uZzZBFU_3rJoF4NkX_v31fX7xe0-clUB
"""

import numpy as np

def build_vocabulary(corpus):
    return sorted({token for text_seq in corpus for token in text_seq})

def build_cooccurrence_matrix(corpus, vocabulary, window_size=1):
    idx_map = {term: pos for pos, term in enumerate(vocabulary)}
    dim = len(vocabulary)
    co_mat = np.zeros((dim, dim), dtype=np.float32)

    for text_seq in corpus:
        seq_len = len(text_seq)
        for center_pos, center_tok in enumerate(text_seq):
            if center_tok not in idx_map:
                continue

            center_id = idx_map[center_tok]

            left_bnd = max(0, center_pos - window_size)
            right_bnd = min(seq_len, center_pos + window_size + 1)

            for neighbor_pos in range(left_bnd, right_bnd):
                if neighbor_pos == center_pos:
                    continue
                neighbor_tok = text_seq[neighbor_pos]
                if neighbor_tok in idx_map:
                    co_mat[center_id, idx_map[neighbor_tok]] += 1.0

    return co_mat

def cosine_similarity(vec1, vec2):
    dot_prod = np.dot(vec1, vec2)
    mag_sq1 = np.sum(vec1 ** 2)
    mag_sq2 = np.sum(vec2 ** 2)

    if mag_sq1 == 0.0 or mag_sq2 == 0.0:
        return 0.0

    return float(dot_prod / np.sqrt(mag_sq1 * mag_sq2))

def most_similar(word, matrix, vocabulary, top_k=5):
    try:
        target_id = vocabulary.index(word)
    except ValueError:
        return []

    target_v = matrix[target_id]

    sim_scores = [
        (vocab_term, cosine_similarity(target_v, matrix[i]))
        for i, vocab_term in enumerate(vocabulary)
        if vocab_term != word
    ]

    return sorted(sim_scores, key=lambda item: item[1], reverse=True)[:top_k]

def word_similarity(word1, word2, matrix, vocabulary):
    try:
        id1 = vocabulary.index(word1)
        id2 = vocabulary.index(word2)
        return cosine_similarity(matrix[id1], matrix[id2])
    except ValueError:
        return 0.0

def compute_matrix_stats(matrix):
    total_cells = np.prod(matrix.shape)
    active_cells = np.sum(matrix != 0)

    empty_ratio = 0.0
    if total_cells > 0:
        empty_ratio = (1.0 - (float(active_cells) / total_cells)) * 100.0

    return {
        "shape": matrix.shape,
        "total_elements": int(total_cells),
        "non_zero": int(active_cells),
        "sparsity_percent": float(empty_ratio)
    }